query getComments ($sub_categoryId:ID $page:Int, $pageSize:Int) {
  comments (
    pagination:{
      page:$page
      pageSize:$pageSize
    }
    filters:{
    sub_category:{id:{eq:$sub_categoryId}}
  }){
    data{
      id
      attributes{
        content
         rate
        createdAt
        updatedAt
        publishedAt
        users_permissions_user{
          data{
            id
            attributes{
              username
            }
          }
        }
      }
    }
    meta{
      pagination{
        total
        page
        pageSize
        pageCount
      }
    }
  }  
}