query getComments ($productId:ID) {
  comments (filters:{
    product:{id:{eq:$productId}}
  }){
    data{
      id
      attributes{
        content
         rate
        createdAt
        updatedAt
        publishedAt
        users_permissions_user{
          data{
            id
            attributes{
              username
            }
          }
        }
      }
    }
  }  
}