query getProducts (
  $page:Int,
  $pageSize:Int,
  $start:Int,
  $limit:Int,
  $productId:ID,
  $categoryId:ID,
  $sub_categoryId:ID, 
  $query:String,
  $sort:[String],
  $colorId:ID,
  $memoryId:ID 
  ){
  products(
    sort:$sort
    pagination:{
      page:$page
      pageSize:$pageSize
      start:$start
      limit:$limit
    }
    filters:{
      id:{eq:$productId}
     category:{id:{eq:$categoryId}}
     sub_category:{id:{eq:$sub_categoryId}}
      color:{id:{eq:$colorId}}
      memory:{id:{eq:$memoryId}}
     name:{contains:$query}
  }){
    meta{
      pagination{
        total
        page
        pageSize
        pageCount
      }
    }
 
    data{
      id
      attributes{
        ...Product
      }
    }
  }  
}