fragment Categories on ComponentSectionCategories{
  id
  title
  description
  categories{
    data{
      id
      attributes{
        name
        slug
        image{
          data{
            attributes{
              ...Image
            }
          }
        }
      }
    }
  }
}