fragment Product on Product{
  name
  slug
  description
  price
  rating
  image{
    data{
      attributes{
        ...Image
      }
    }
  }
  collection{
    data{
      attributes{
        ...Collection
      }
    }
  }
  color{
    data{
      id
      attributes{
        title
        color
      }
    }
  }
  memory{
    data{
      id
      attributes{
        value
        title
      }
    }
  }
  brand{
    data{
      id
    }
  }
  category{
    data{
      id
      
    }
  }
  sub_category{
    data{
      id
      attributes{
        colors{
          data{
            id
            attributes{
              title
              color
            }
          }
        }
        memories{
          data{
            id
            attributes{
              title
              value
            }
          }
        }
      }
    }
  }  
}