fragment SliderCollection on ComponentSectionSliderCollection{
  id
  title
  description
  collection{
    data{
      id
      attributes{
        ...Collection
        
        products{
          data{
            id
            attributes{
              ...Product
            }
          }
        }
      }
    }
  }
}