query getGlobal {
  global{
    data{
      attributes{
        seo{
          ...Seo
        }
        menu{
          ...Link
        }
        social{
          ...Link
        }
        service{
          ...Link
        }
      }
    }
  }
}