query getUserByEmail ($email:String!){
  usersPermissionsUsers(
  filters:{
    email:{eq:$email}
  }){
    data{
      id
      attributes{
        username
        email
        blocked
      }
    }
  }
}