query getOrderByUserId ($userId:ID!){
  orders(filters:{users_permissions_user:{id:{eq:$userId}}}){
    data{
      id
      attributes{
        status
        total_price
        total_quantity
        createdAt
        updatedAt
        users_permissions_user{
          data{
            id
          }
        }
        delivery{
          data{
            id
            attributes{
              title
              price
            }
          }
        }
        address{
          data{
            id
            attributes{
              title
            }
          }
        }
        cart{
          id
          quantity
          product{
            data{
              id
              attributes{
                ...Product
              }
            }
          }
        }
      }
    }
  }
}