query getCategory($id:ID){
  category(id:$id){
    data{
      id
      attributes{
        name
        slug
        products{
          data{
            id
            attributes{
              ...Product
            }
          }
        }
      }
    }
  }
}